# Twitter API Credentials - Replace with yours
TWITTER_API_KEY = "MNTeN4r1x7cgWUcaKHzNyV1q2"
TWITTER_API_SECRET = "zBQ9kszg3HWwzNJczVVDkUmOqcc0scFykeoRR1t4Cwf8YxBy20"
TWITTER_ACCESS_TOKEN = "AAAAAAAAAAAAAAAAAAAAAGWKxwEAAAAAPbvcQD7dZ8kLW%2FlQk9DgYYb4uH0%3DXxfmciqN7a2v2BxRzlzlytjsQ8ONfner9YUIABnUCqIFhYbuma"
TWITTER_ACCESS_TOKEN_SECRET = ""
